### ISSUE TITLE
darshan-runtime autoconf tests don't properly detect MPI const usage for all compilers

### ISSUE THREAD

**Issue by shanedsnyder** [darshan-hpc/darshan#390]
There seems to be some difference between GNU and Intel compilers in terms of whether errors or warnings are issued for redefinition of existing MPI prototypes. Our autoconf tests try to redefine existing MPI prototypes to determine whether they are using const for some input parameters or not. For Intel compilers specifically, only warnings are issued when redefining MPI prototypes with different signatures (i.e., const vs no const), which causes our autconf tests to behave unexpectedly. We need to make sure compiler warnings are treated as errors for these tests, specifically, to avoid this issue and to allow us to correctly detect whether MPI prototypes are using const or not.

**Comment by wkliao** [comment]
Hi, Shane

Another solution is to check MPI_VERSION in the header file mpi.h. The change of using 'const' modifier for MPI-IO APIs starts from MPI standard 3.0. See the following commit.
https://github.com/darshan-hpc/darshan/commit/7da8cb19209dcf79878571b5cfbdbc5f0c4e43e4

**Comment by carns** [comment]
@wkliao I'm a little nervous about keying off of MPI_VERSION, just because it relies on the MPI implementor toggling the value of that definition at the same time that they toggled const correctness in their release history.  It may be safer to feature test (despite bugs like this one) rather than version check?

**Comment by carns** [comment]
(fwiw part of my mentality on this is from maintaining the old pvfs2 kernel module years ago; distributions used to be notorious for backporting capabilities to old kernels, so version checks were unreliable when checking for kernel features)

**Comment by wkliao** [comment]
MPI_VERSION is a required constant by MPI standard. If an MPI vendor failed to implement its library by abiding to the MPI standard, then it is the vendor's fault. So, I believe using it in Darshan is safe. Besides, I do not know a portable way to test this at configure time, as different C compilers use different flags to treat a warning as an error.

FYI. I created a PR in MPICH with the same fix and it has been merged into the official release.
https://github.com/pmodels/mpich/commit/2d963546b6e0166db2eb5f42070a8d6052cde1cb#diff-c97895a0925dec5ed8c1ca9d1cb4577e06f3fc3a3d4940471af429b9439789f0

**Comment by carns** [comment]
@wkliao ok, we'll give it a shot.  I'm back to looking at your autotools branch (which already has this change) now that the github migration is complete.

re: the compiler warning/error options, in theory the darshan library itself should be built with gcc (for maximum compatibility on HPC systems that support multiple compilers and tool chains), but we've always advertised that as a recommendation rather than a requirement.

**Comment by wkliao** [comment]
I am not aware GNU is preferable compiler by Darshan.
Feel free to discard my suggestion. I guess this issue is more critical for ROMIO.
