### ISSUE TITLE
MAINT: Use Type Hints in PyDarshan if sensible

### ISSUE THREAD

**Issue by jakobluettgau** [darshan-hpc/darshan#406]
Initially, when developing PyDarshan it was unclear if Python 2 would need to be supported for compatibility to some sites. The current code base therefor did not use type hints. Going forward, and since we are building binary wheels for python 3.6+ only anyways, it seems sensible to start adding them. https://www.python.org/dev/peps/pep-0484/

**Comment by tylerjereddy** [comment]
Good idea, I did draft in type hints where I could in #397, though I haven't gone as far as trying to use the stubs/types that i.e., pandas and NumPy teams provide. At least we can do it incrementally in any case.

Another thing we might want to bring up with Shane and Phil is setting up some simple CI for pydarshan, perhaps only on the `pydarshan-devel` branch for now--maybe building `darshan-util`, then `pydarshan`, then running the `pytest` suite for a few versions of Python (3.7-3.9). And maybe running `mypy` or whatever type checker you like to use. I think I suggested CI may be good for @nawtrey to look into when time permits (though this is a separate matter from this issue).

**Comment by carns** [comment]
CI is a great idea, especially if we can use Github capabilities for this now that Darshan is fully hosted on github.  I don't have any experience setting up such a thing, though.

My only feedback (based on experience with other projects) is that it is handy to be able to run this sort of test equally well from both github and the command line, so that you can "pre-screen" if your modifications are clean locally without waiting for PR tests to run, which could stall for unrelated reasons.

**Comment by tylerjereddy** [comment]
I'll close this since we now have initial type hints in some parts of the code and the CI is running `mypy` on the `darshan` and `tests` folders to check the type hints in Python code.

We can open separate focused issues if there are specific areas of the code base that would benefit particularly from type hints, etc.
