### ISSUE TITLE
decide on a HTML template engine/framework for pydarshan job summaries

### ISSUE THREAD

**Issue by shanedsnyder** [darshan-hpc/darshan#461]
Based on discussions in #445 and in meetings, we have decided to try to make an HTML-based PyDarshan job summary report, rather than something PDF-based. This will likely give us the flexibility we need to let the summary report format change over time or as a result of contents of a given log file (e.g., module summary sections that may or may not be present in given log files), without wasting too much effort in maintaining a sane PDF report layout.

There are a number of templating engines for Python worth investigating to see if any is a more obvious fit for what we are trying to accomplish. Things like [Jinja](https://jinja.palletsprojects.com/en/3.0.x/) and [Genshi](https://genshi.edgewall.org/) are examples of popular engines in this space. @kevin-harms has already investigated Genshi a bit in producing HTML job reports in #386 -- if nothing obvious stands out in comparing diifferent engines, maybe we could just start with the code in that PR as a starting point.

At a high-level, we need the engine to generate HTML templates based on the contents of a given Darshan log. Some components of the job summary reports will always be present (e.g., high-level job metadata and presumably the I/O activity heatmap), while other components will only be included if certain modules are enabled in the log (or based on other conditions). We also need to understand exactly what format our figures, tables, etc. need to be in before embedding them into a report -- I think the Genshi example in #386 converts mpl figures to raw I/O buffers that can be embedded/referenced in the HTML. We should formulate some best practice for our approach to embedding different types of data so that we have a game plan for adding components to the report going forward.

Let's use this issue to track discussion on different frameworks to determine whether any make for obvious choices. Once this is sorted out, we can make progress on implementing different components of the job summary reports.

**Comment by nawtrey** [comment]
After looking over Genshi, Jinja, and another HTML engine, [Mako](https://www.makotemplates.org/), here are some notes on their similarities/differences. 

HTML Engine Differences
-------------------------
`Genshi`:
 - Doesn't officially support Python 3, although I don't know what features we would be missing as a result
 - Decent documentation
 - XML-focused tool with templating capabilities
 - Least amount of GitHub activity of the 3 (https://github.com/edgewall/genshi)

`Jinja`:
 - Supports Python 2 and 3
 - Allegedly good documentation
 - Considered to be faster than `Genshi` for HTML things since `Genshi` is more focused around XML
 - [GitHub page](https://github.com/pallets/jinja)

`Mako`:
 - Supports Python 2 and 3
 - Most Python-oriented of the 3, most of the syntax is similar to Python
- Considered to be the fastest of the 3 for HTML. They have a header on their website that states "Mako is used by reddit.com where it delivers over one billion page views per month"
 - [GitHub page](https://github.com/zzzeek/mako)

HTML Engine Similarities:
-------------------------
 - All are easy to install (pip installable)
 - All offer conditionals, function writing, variable assignment, including code from other files, etc. 

Summary
=======
As far as the templating packages are concerned, I'm open to using any of them. I think `Mako` would probably be easiest for the Python devs (myself included) due to its pythonic syntax. At this point I have working `Genshi` and `Mako` templates, so the barriers to start developing with either are about the same. 

I'm also concerned about Genshi's lack of support for Python 3, although I'm not sure what that means feature-wise. About 3 years ago their team mentioned that the development version supported Python 3, but that still hasn't been moved into the release version, so I'm not sure how much work is being done there. Their GitHub page does seem to be the least active of the 3, although none of them are super active.

**Comment by nawtrey** [comment]
There is interest in programmatically generating our HTML template such that we don't have to maintain an HTML file at all (or very little), and as far as I can tell the HTML engines above don't have support for something like that. They allow you to write conditionals and for-loops inside your template to make it simpler, but if we were to write python functions to generate the template there would still be a fair amount of HTML in the strings we generate.

To get away from that, I did find a package [Yattag](https://www.yattag.org/) which provides a  pythonic interface for writing HTML. It appears their [GitHub page](https://github.com/leforestier/yattag) doesn't have much activity, but I thought it was worth mentioning.

**Comment by nawtrey** [comment]
In the meeting today we discussed the HTML engines above. It looks like we'll be going with Mako for templating, and not working with Yattag unless there is a clear justification for it in the future.

**Comment by kevin-harms** [comment]
Mako looks good. The <%def> and <%block> tags should allow use to define a basic module template which a user can then just add to the main template for a new module with minimal work. We could also have some module specific templates as they get developed.

**Comment by tylerjereddy** [comment]
We're going with `mako` so I think I can close this for now. We can re-open if we run into some intractable problems, but I doubt it at this point.
