### ISSUE TITLE
BUG: Sporadic "partial data" flag observed in summary reports for various logs 

### ISSUE THREAD

**Issue by nawtrey** [darshan-hpc/darshan#520]
Upon generating a summary report for `sample-dxt-simple.darshan` I'm seeing different "partial data" flags in the module table. Sometimes it says that every module has partial data, sometimes it says none, and other times it's a mix. 

Here are 3 different reports generated from the same code that all show different flags: [test_reports.tar.gz](https://github.com/darshan-hpc/darshan/files/7340228/test_reports.tar.gz) 

For each log the flags should be consistent. @shanedsnyder seemed to think none of the in-tree logs would have partial data in the first place, so the expectation is we shouldn't see `partial data` tag for any of the modules.

**Comment by tylerjereddy** [comment]
I don't need a new test to see that there is a problem on my end--the regular suite seems to consistently fail locally on Python 3.9 after a clean rebuild of the whole C/Python stack (see below). 

`pytest --import-mode=importlib `

```
========================================================================================================================================================= FAILURES =========================================================================================================================================================
_______________________________________________________________________________________________________________________________________________________ test_modules _______________________________________________________________________________________________________________________________________________________
[gw2] darwin -- Python 3.9.5 /Users/treddy/python_venvs/python_395/bin/python

    def test_modules():
        """Sample for an expected number of modules."""
    
        report = darshan.DarshanReport("tests/input/sample.darshan")
    
        # check if number of modules matches
        assert 4 == len(report.modules)
        assert 154 == report.modules['MPI-IO']['len']
>       assert False == report.modules['MPI-IO']['partial_flag']
E       assert False == True

tests/test_report.py:58: AssertionError
```

Maybe @shanedsnyder can check this potential patch -- seems to restore test passing. Maybe you get sporadic results if only rebuild the Python part but don't get the updated C `struct` (so you confusingly get an index value for the flag, that would be my guess).

```diff
diff --git a/darshan-util/darshan-logutils.h b/darshan-util/darshan-logutils.h
index 152175c..988ee9a 100644
--- a/darshan-util/darshan-logutils.h
+++ b/darshan-util/darshan-logutils.h
@@ -73,8 +73,8 @@ struct darshan_mod_info
     const char *name;
     int  len;
     int  ver;
-    int  idx;
     int partial_flag;
+    int  idx;
 };
 
 struct darshan_name_record_info
diff --git a/darshan-util/pydarshan/darshan/backend/api_def_c.py b/darshan-util/pydarshan/darshan/backend/api_def_c.py
index c1fa4e7..69bf508 100644
--- a/darshan-util/pydarshan/darshan/backend/api_def_c.py
+++ b/darshan-util/pydarshan/darshan/backend/api_def_c.py
@@ -19,8 +19,8 @@ struct darshan_mod_info
     char *name;
     int        len;
     int        ver;
-    int        idx;
     int partial_flag;
+    int        idx;
 };
 
 /* from darshan-log-format.h */
```

**Comment by tylerjereddy** [comment]
I can see why CI passed--I reinstalled the C/Python stack from scratch and ran that test 250 times, and it passed:

`pytest --import-mode=importlib --count=250  -n 8 tests/test_report.py::test_modules `

`250 passed in 3.09s`

Probably some mind bending stuff with the `struct` C ABI ordering out of whack.

The only way I can see the **runtime** behavior flip-flop as described in the original issue is if I intentionally build `pydarshan` with the latest version after first building the C library with a version that precedes Shane's recent C `struct` changes:

`pytest --import-mode=importlib --count=250  -n 8 tests/test_report.py::test_modules `

`176 failed, 74 passed in 3.18s`

So, Nik probably didn't rebuild the C library before testing in Python, which normally might be safe, but when the C ABI changes it is not safe.

Still, the C `struct` member ordering probably does need a fixup.

**Comment by shanedsnyder** [comment]
Ahh, good catch, guys. I think @tylerjereddy explanation makes sense.

Sounds like it's just a result of using an older darshan-util library that's causing some ABI issues since I changed a structure definition there for these changes. There is a check in pydarshan that makes sure the darshan-util library version that is loaded matches the one that was used to generate the API definitions passed to CFFI, but that isn't working because I haven't actually bumped the darshan-util library version (i.e., it's still 3.3.1, the version of our last release) -- we don't typically do that until we're finalizing a release and sure which version we want to call it. I should have realized that would have caused an issue for you guys and mentioned a rebuild of the library was needed, my bad.

I don't think we need to be concerned about backwards compatibility here, either. pydarshan builds are currently tied to specific darshan-util versions, with no backwards compatibility provided to previous darshan-util versions. We support backwards compatibility for log file format versions within the darshan-util library, which is much more important, but don't really care about backwards compatibility of darshan-util ABI.

Assuming @nawtrey is now able to workaround after rebuilding the library, I'm inclined just to ultimately rectify this once things are merged into main and we start bumping version numbers as part of the next release. That might be simplest, especially if there are more potential changes to darshan-util API in the future, but let me know if there's other concerns you guys have and maybe we can try something else.
