### ISSUE TITLE
BUG: ReportFigure ignores fig_width for large figs

### ISSUE THREAD

**Issue by tylerjereddy** [darshan-hpc/darshan#717]
`ReportFigure` has a `fig_width` argument that is documented as:

> fig_width : the width of the figure in pixels. 

Let's try adding in the "data access by category" figure to the report and setting its width to a single pixel:

```diff
diff --git a/darshan-util/pydarshan/darshan/cli/summary.py b/darshan-util/pydarshan/darshan/cli/summary.py
index 7fbc8fad..6b64069d 100644
--- a/darshan-util/pydarshan/darshan/cli/summary.py
+++ b/darshan-util/pydarshan/darshan/cli/summary.py
@@ -22,6 +22,7 @@ from darshan.experimental.plots import (
     plot_common_access_table,
     plot_access_histogram,
     plot_opcounts,
+    data_access_by_filesystem,
 )
 
 darshan.enable_experimental()
@@ -458,6 +459,20 @@ class ReportData:
                 )
                 self.figures.append(opcount_fig)
 
+        #########################
+        # Data Access by Category
+        if not {"POSIX", "STDIO"}.isdisjoint(set(self.report.modules)):
+            data_access_by_cat_fig = ReportFigure(
+                section_title="Data Access by Category",
+                fig_title="",
+                fig_func=data_access_by_filesystem.plot_with_report,
+                fig_args=dict(report=self.report, num_cats=8),
+                fig_description="",
+                fig_width=1,
+            )
+            self.figures.append(data_access_by_cat_fig)
+
+
```

The result is still way bigger than any other figure/image in the html file generated with `python -m darshan summary /Users/treddy/github_projects/darshan-logs/darshan_logs/e3sm_io_heatmaps_and_dxt/e3sm_io_heatmap_only.darshan`:

![image](https://user-images.githubusercontent.com/7903078/164276632-a0202322-83db-4495-a686-519024000e6b.png)

**Comment by nawtrey** [comment]
It appears this only happens when `fig_title=""`. If you populate the field `fig_width` should work again. I think it's because we are using the figure title as the alternate text in the `<img>` tag, so when it isn't present we get something like this:

```
<img src=data:ima...= alt= width=350>
```

which must be preventing the width from being set properly. Strictly speaking we don't _need_ the alternate text, so simply removing that should prevent this from happening. Alternatively we could have a default figure title. 

Also, I agree we could avoid this entirely by using the figure data itself to set the width based on a predetermined page width or something like that. I do think having an option for setting the figure sizing is useful, particularly when trying to "print to PDF", but I'm sure there are less clunky ways of achieving that then manually setting a figure width for each figure type.

**Comment by tylerjereddy** [comment]
Sounds like there's a bug in the propagation of the empty field then--checking around online:

> Decorative images require the addition of an empty or null alt attribute in the HTML Code View that will tell the screen reader to skip over the image. An empty alt attribute is written as alt=” ” with a space between the double quotes.

That's similar to a default alt entry, but a bit more correct--if I leave it empty, I probably wanted it empty for prototyping so propagating that through makes sense I think.

**Comment by nawtrey** [comment]
Yeah we can probably add a small fix for that then.

**Comment by tylerjereddy** [comment]
Nik fixed this in gh-720, so I'll close it.

When we're back to working with the `main` branch for Python development, the GitHub auto-close feature should save us some time on manual closing.
