### ISSUE TITLE
BUG: `test_adjust_for_colorbar` failing in some environments

### ISSUE THREAD

**Issue by shanedsnyder** [darshan-hpc/darshan#742]
Notably, tests that run as part of the cibuildwheel test phase are failing for CPython 3.7 manylinux x86_64 (using an Ubuntu runner):

https://github.com/darshan-hpc/darshan/runs/6457965128?check_suite_focus=true

**Comment by tylerjereddy** [comment]
I've seen it before, needs `matplotlib` pinned to `<3.5` because of a `seaborn` issue. Could perhaps be productively expressed in the build system and/or at early import time. You might want to make sure the testing scenario for `cibuildwheel` uses an appropriate version of `matplotlib` for now.

We have an issue open here: gh-479

There's a comment mentioning that issue in our main ci file too.

**Comment by tylerjereddy** [comment]
You could also just conditionally `xfail` it if matplotlib version is too great at test runtime.

**Comment by shanedsnyder** [comment]
Thanks for the pointer -- I'll close this as it looks to be a duplicate.
