### ISSUE TITLE
Darshan modules records order?

### ISSUE THREAD

**Issue by jesse-r-s-hines** [darshan-hpc/darshan#814]
In `darshan-parser` output and `PyDarshan`, is there any defined order of the records? In particular will records with the same `recordid` and `rank` that show up in multiple modules show up in the same relative order in each module? I am unable to find any documentation regarding the order of the logs.

I need to aggregate some data for each file from several modules, and if the records show up in each module in the same order I could do so without loading the whole darshan log into memory.

**Comment by carns** [comment]
Hi @jesse-r-s-hines .  Unfortunately for your use case, the modules probably often happen to have records in the same order, but it's not guaranteed.

We should probably document this, but the ordering of records is intentionally undefined so that the the runtime instrumentation modules have the freedom to emit data in a write-optimized manner (however makes sense for that particular module) in order to minimize job runtime overhead.  The post-processing utilities can the elect to sort or not depending on the use case.

In practice (but again not explicitly defined or enforced) all of our current modules happen to at least order by rank because that happens to be the most sensible way to coordinate collective operations when Darshan starts aggregating data.

The recordids on the other hand can get out of order across modules just by luck of the draw because they are emitted in the order that the module observes the corresponding file.  This can get skewed as you cross API (and thus Darshan module) boundaries either because of timing luck or because of library transformations like MPI's deferred opens or collective buffering.

**Comment by jesse-r-s-hines** [comment]
I'll have to use an external sort of since sort then. Thanks for the info!
