### ISSUE TITLE
darshan-dxt-parser  backward compatibility

### ISSUE THREAD

**Issue by wkliao** [darshan-hpc/darshan#842]
I tried to run `darshan-dxt-parser` using a log file created by an early version
of Darshan and got the following errors.
```
Error: Invalid DXT POSIX module version number (got 2)
Error: failed to parse DXT_POSIX module record.
```
Is this backward compatibility not supported?

**Comment by shanedsnyder** [comment]
What version of Darshan did you use to generate the log? And what version are you using to try and parse it? darshan-util can be newer than the darshan-runtime version (i.e., backwards compatibility should be supported).

Also, if the log was originally generated using a development version of Darshan, it's possible the file format used to generate the log has since changed and is no longer parsable. I only mention that in case the log was maybe generated with an earlier version of the PnetCDF module branch -- in that case you might need to check out specific git commits to properly retrieve the data...

**Comment by wkliao** [comment]
Thanks. My log file was indeed generated from a development version.
After using 3.2.1 to regenerate the log file, there is no more error.
